from __future__ import annotations

from collections import OrderedDict

from .models import PatternTrack, TrackAnalysis


def _event_token(track_name: str) -> str:
    if track_name == "kick":
        return "bd"
    if track_name == "snare":
        return "sd"
    if track_name == "hat":
        return "hh"
    return track_name[:2]


def _track_to_two_bar_step_string(track: PatternTrack, steps_per_bar: int, loop_bars: int) -> str:
    total_steps = steps_per_bar * loop_bars
    if total_steps <= 0:
        return ""

    loop_grid = [["~" for _ in range(steps_per_bar)] for _ in range(loop_bars)]
    token = _event_token(track.name)

    for event in track.events:
        loop_bar = event.bar % loop_bars
        step = event.step_in_bar
        if 0 <= loop_bar < loop_bars and 0 <= step < steps_per_bar:
            loop_grid[loop_bar][step] = token

    bar_strings = [" ".join(bar_steps) for bar_steps in loop_grid]
    return " ".join(f"[{bar}]" for bar in bar_strings)


def _drum_synth_line(track_name: str, step_pattern: str) -> str:
    """Convert a step-pattern string into a correct Strudel mini-notation line.

    The step_pattern uses tokens like 'bd', 'sd', 'hh' from the analyzer.
    We replace them with proper Strudel values and emit a single .note() or
    .sound() call — no double-chaining that overrides the pattern.
    """
    if track_name == "kick":
        # kick: replace "bd" → "c2" for a sub-bass sine hit
        note_pattern = step_pattern.replace("bd", "c2")
        return (
            f'note("{note_pattern}").sound("sine")'
            ".decay(0.12).sustain(0).lpf(180).gain(0.95)"
        )
    if track_name == "snare":
        # snare: replace "sd" → "white" for filtered noise burst
        sound_pattern = step_pattern.replace("sd", "white")
        return (
            f'sound("{sound_pattern}")'
            ".decay(0.06).sustain(0).hpf(1500).gain(0.35).room(0.04)"
        )
    # hat: replace "hh" → "white" for short high noise
    sound_pattern = step_pattern.replace("hh", "white")
    return (
        f'sound("{sound_pattern}")'
        ".decay(0.03).sustain(0).hpf(8000).gain(0.18).crush(8)"
    )


def _bass_synth_line(track: PatternTrack, steps_per_bar: int, loop_bars: int) -> str:
    loop_steps = steps_per_bar * loop_bars
    if track.notes and len(track.notes) == loop_steps:
        bar_chunks = [
            " ".join(track.notes[bar * steps_per_bar : (bar + 1) * steps_per_bar])
            for bar in range(loop_bars)
        ]
        bass_pattern = " ".join(f"[{chunk}]" for chunk in bar_chunks)
    elif track.notes:
        bass_pattern = " ".join(track.notes)
    else:
        fallback = ["~"] * loop_steps
        beat_step = max(1, steps_per_bar // 4)
        for i in range(0, loop_steps, beat_step):
            fallback[i] = "c1"
        bar_chunks = [
            " ".join(fallback[bar * steps_per_bar : (bar + 1) * steps_per_bar])
            for bar in range(loop_bars)
        ]
        bass_pattern = " ".join(f"[{chunk}]" for chunk in bar_chunks)

    return (
        f'note("{bass_pattern}").sound("sawtooth").decay(0.18).release(0.08).sustain(0.15)'
        ".lpf(700).lpq(1.5).gain(0.45).room(0.12).delay(0.05)"
    )


def analysis_to_strudel(analysis: TrackAnalysis) -> str:
    lines: list[str] = []
    lines.append("// Generated by techno-strudel-converter")
    lines.append(f"// Source: {analysis.path}")
    lines.append(f"// Tempo: {analysis.grid.tempo:.2f} BPM")
    lines.append(
        f"// Loop: {analysis.grid.loop_bars} bars x {analysis.grid.steps_per_bar} steps"
    )
    lines.append("")

    if analysis.notes:
        for note in analysis.notes:
            lines.append(f"// {note}")
        lines.append("")

    lines.append(f"setcps({analysis.grid.tempo / 60.0:.4f})")
    lines.append("")
    lines.append("stack(")
    ordered_tracks = OrderedDict(
        (name, track)
        for name, track in analysis.tracks.items()
        if name in {"kick", "snare", "hat", "bass"}
    )

    rendered_lines: list[str] = []
    for name, track in ordered_tracks.items():
        if name == "bass":
            rendered_lines.append(
                _bass_synth_line(track, analysis.grid.steps_per_bar, analysis.grid.loop_bars)
            )
        else:
            pattern = _track_to_two_bar_step_string(
                track, analysis.grid.steps_per_bar, analysis.grid.loop_bars
            )
            rendered_lines.append(_drum_synth_line(name, pattern))

    for index, rendered in enumerate(rendered_lines):
        suffix = "," if index < len(rendered_lines) - 1 else ""
        lines.append(f"  {rendered}{suffix}")
    lines.append(")")
    lines.append("")

    if analysis.sections:
        lines.append("// Sections")
        for section in analysis.sections:
            lines.append(
                f"// {section.label}: bars {section.start_bar}-{section.end_bar}, confidence {section.confidence:.2f}"
            )

    return "\n".join(lines).rstrip() + "\n"
